version: '3.9'

networks:
    resume_net: 

services:
  web:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: '${APP_NAME}-web'
    ports:
      - "8083:80"
    working_dir: /var/www/html
    environment:
      - ALLOW_OVERRIDE=true
       
    volumes:
      - ./app:/var/www/html/
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini

    depends_on:
      db:
        condition: service_healthy
    networks:
      - resume_net    
    
  db:
    image: mariadb:10.5.9
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Secreto2021
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=resume
    ports:
      - '8890:3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=Secreto2021
      interval: 5s
      retries: 5  
    networks:
      - resume_net    

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: '${APP_NAME}-db-admin'
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - db_admin_data:/var/www/html
    networks:
      - resume_net

volumes:
  db_data:      
  db_admin_data: